### ISSUE TITLE
<Icon /> does not forward the ref

### ISSUE THREAD

**Issue by hrasoa** [iconify-design/iconify-react#20]
I should get the svg dom element in the ref.

Demo:

https://9ghol.csb.app/

```
index.js:27 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `App`.
    at Icon$1 (https://9ghol.csb.app/node_modules/@iconify/react-with-api/dist/icon.esm.js:2054:10)
    at div
    at App (https://9ghol.csb.app/src/App.js:24:34)
```

**Comment by hrasoa** [comment]
Moved to https://github.com/iconify/iconify/issues/57
